schemaVersion: "2.0.0"

fileExistenceTests:

- name: 'File: setup.py'
  path: '/usr/src/app/setup.py'
  shouldExist: true

commandTests:

- name: "Command: python"
  command: "python"
  args: ["--version"]
  expectedOutput: ["Python 3.1"]
  exitCode: 0

- name: "Command: container entrypoint"
  command: "python"
  args: ["-u", "/usr/local/bin/python-mysql-exporter"]
  expectedError: ["the following arguments are required: --project-id/-p, --jira-project/-j"]
  exitCode: 2
